services:
  web:
    image: python:alpine
    working_dir: /app
    expose:
      - 8000
    command: sh -c "
      pip install django django-environ gunicorn &&
      gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 6969:80
    depends_on:
      - web